/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AirdropRouteImport } from './routes/airdrop'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as TokenRouteImport } from './routes/token'
import { Route as WorldRouteImport } from './routes/world'
import { Route as ApiAgentsRouteImport } from './routes/api/agents'
import { Route as ApiAssistantGrantRouteImport } from './routes/api/assistant-grant'
import { Route as ApiAvatarModelRouteImport } from './routes/api/avatar-model'
import { Route as ApiLeaderboardRouteImport } from './routes/api/leaderboard'
import { Route as RHandleRouteImport } from './routes/r/$handle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AirdropRoute = AirdropRouteImport.update({
  id: '/airdrop',
  path: '/airdrop',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRoute = ClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenRoute = TokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsRoute = ApiAgentsRouteImport.update({
  id: '/api/agents',
  path: '/api/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantGrantRoute = ApiAssistantGrantRouteImport.update({
  id: '/api/assistant-grant',
  path: '/api/assistant-grant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvatarModelRoute = ApiAvatarModelRouteImport.update({
  id: '/api/avatar-model',
  path: '/api/avatar-model',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeaderboardRoute = ApiLeaderboardRouteImport.update({
  id: '/api/leaderboard',
  path: '/api/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RHandleRoute = RHandleRouteImport.update({
  id: '/r/$handle',
  path: '/r/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/airdrop': typeof AirdropRoute
  '/arena': typeof ArenaRoute
  '/claim': typeof ClaimRoute
  '/collection': typeof CollectionRoute
  '/launch': typeof LaunchRoute
  '/leaderboard': typeof LeaderboardRoute
  '/setup': typeof SetupRoute
  '/token': typeof TokenRoute
  '/world': typeof WorldRoute
  '/api/agents': typeof ApiAgentsRoute
  '/api/assistant-grant': typeof ApiAssistantGrantRoute
  '/api/avatar-model': typeof ApiAvatarModelRoute
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/r/$handle': typeof RHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/airdrop': typeof AirdropRoute
  '/arena': typeof ArenaRoute
  '/claim': typeof ClaimRoute
  '/collection': typeof CollectionRoute
  '/launch': typeof LaunchRoute
  '/leaderboard': typeof LeaderboardRoute
  '/setup': typeof SetupRoute
  '/token': typeof TokenRoute
  '/world': typeof WorldRoute
  '/api/agents': typeof ApiAgentsRoute
  '/api/assistant-grant': typeof ApiAssistantGrantRoute
  '/api/avatar-model': typeof ApiAvatarModelRoute
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/r/$handle': typeof RHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/airdrop': typeof AirdropRoute
  '/arena': typeof ArenaRoute
  '/claim': typeof ClaimRoute
  '/collection': typeof CollectionRoute
  '/launch': typeof LaunchRoute
  '/leaderboard': typeof LeaderboardRoute
  '/setup': typeof SetupRoute
  '/token': typeof TokenRoute
  '/world': typeof WorldRoute
  '/api/agents': typeof ApiAgentsRoute
  '/api/assistant-grant': typeof ApiAssistantGrantRoute
  '/api/avatar-model': typeof ApiAvatarModelRoute
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/r/$handle': typeof RHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/airdrop'
    | '/arena'
    | '/claim'
    | '/collection'
    | '/launch'
    | '/leaderboard'
    | '/setup'
    | '/token'
    | '/world'
    | '/api/agents'
    | '/api/assistant-grant'
    | '/api/avatar-model'
    | '/api/leaderboard'
    | '/r/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/airdrop'
    | '/arena'
    | '/claim'
    | '/collection'
    | '/launch'
    | '/leaderboard'
    | '/setup'
    | '/token'
    | '/world'
    | '/api/agents'
    | '/api/assistant-grant'
    | '/api/avatar-model'
    | '/api/leaderboard'
    | '/r/$handle'
  id:
    | '__root__'
    | '/'
    | '/airdrop'
    | '/arena'
    | '/claim'
    | '/collection'
    | '/launch'
    | '/leaderboard'
    | '/setup'
    | '/token'
    | '/world'
    | '/api/agents'
    | '/api/assistant-grant'
    | '/api/avatar-model'
    | '/api/leaderboard'
    | '/r/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AirdropRoute: typeof AirdropRoute
  ArenaRoute: typeof ArenaRoute
  ClaimRoute: typeof ClaimRoute
  CollectionRoute: typeof CollectionRoute
  LaunchRoute: typeof LaunchRoute
  LeaderboardRoute: typeof LeaderboardRoute
  SetupRoute: typeof SetupRoute
  TokenRoute: typeof TokenRoute
  WorldRoute: typeof WorldRoute
  ApiAgentsRoute: typeof ApiAgentsRoute
  ApiAssistantGrantRoute: typeof ApiAssistantGrantRoute
  ApiAvatarModelRoute: typeof ApiAvatarModelRoute
  ApiLeaderboardRoute: typeof ApiLeaderboardRoute
  RHandleRoute: typeof RHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airdrop': {
      id: '/airdrop'
      path: '/airdrop'
      fullPath: '/airdrop'
      preLoaderRoute: typeof AirdropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token': {
      id: '/token'
      path: '/token'
      fullPath: '/token'
      preLoaderRoute: typeof TokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents': {
      id: '/api/agents'
      path: '/api/agents'
      fullPath: '/api/agents'
      preLoaderRoute: typeof ApiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant-grant': {
      id: '/api/assistant-grant'
      path: '/api/assistant-grant'
      fullPath: '/api/assistant-grant'
      preLoaderRoute: typeof ApiAssistantGrantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/avatar-model': {
      id: '/api/avatar-model'
      path: '/api/avatar-model'
      fullPath: '/api/avatar-model'
      preLoaderRoute: typeof ApiAvatarModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leaderboard': {
      id: '/api/leaderboard'
      path: '/api/leaderboard'
      fullPath: '/api/leaderboard'
      preLoaderRoute: typeof ApiLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$handle': {
      id: '/r/$handle'
      path: '/r/$handle'
      fullPath: '/r/$handle'
      preLoaderRoute: typeof RHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AirdropRoute: AirdropRoute,
  ArenaRoute: ArenaRoute,
  ClaimRoute: ClaimRoute,
  CollectionRoute: CollectionRoute,
  LaunchRoute: LaunchRoute,
  LeaderboardRoute: LeaderboardRoute,
  SetupRoute: SetupRoute,
  TokenRoute: TokenRoute,
  WorldRoute: WorldRoute,
  ApiAgentsRoute: ApiAgentsRoute,
  ApiAssistantGrantRoute: ApiAssistantGrantRoute,
  ApiAvatarModelRoute: ApiAvatarModelRoute,
  ApiLeaderboardRoute: ApiLeaderboardRoute,
  RHandleRoute: RHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
